= BigClown Documentation Repository
:gh-name: bigclownlabs/bc-doc

ifdef::env-github[]
image:https://travis-ci.org/{gh-name}.svg?branch=master["Deploy Status", link="https://travis-ci.org/{gh-name}"]
endif::env-github[]


IMPORTANT: If you are looking for documentation, please proceed to this address: *http://doc.bigclown.com*


== Preface

We use AsciiDoc text document format for writing documentation.
AsciiDoc is a lightweight markup language that helps writer to stay focused on the content.
We translate AsciiDoc format to HTML using Asciidoctor which is a new implementation of text processor for AsciiDoc.

More information about this technology can be found on http://asciidoctor.org[Asciidoctor’s website].


== Writer’s setup

This chapter describes a writer’s setup for seamless work.

The goal is to achieve the following functionality:

* HTML output with proper formatting and correct hyperlinks,
* live preview in the web browser,
* page auto-reload on file save.

System requirements:

* Ruby ≥ 2.2.2 with development files,
* C/C++ build environment with make and gcc (for building native extensions of Ruby gems).


=== Installation

NOTE: The following procedure has been tested on Ubuntu 16.04 LTS.

. Install Git, Ruby and development files for Ruby
[loweralpha]
.. on Alpine Linux:
+
    apk add git ruby ruby-io-console ruby-json build-base libffi-dev ruby-dev

.. on Ubuntu:
+
    sudo apt-get install git ruby ruby-dev build-essential

. Clone the documentation repository from GitHub:
+
    git clone https://github.com/bigclownlabs/bc-doc.git

. Switch to the cloned repository:
+
    cd bc-doc

. Check system dependencies and install required gems into `./.gem` directory:
+
    ./script/bootstrap

. Run Middleman server:
+
    ./script/server

. Open the web browser with this URL: http://localhost:4567.

. Directly modify AsciiDoc files in the *source* directory in your favourite text editor and see the immediate effect in the browser.

. Good luck with undisturbed writing!


== Site layout

=== Navigation

Navigation tree is generated automatically from the content (pages) and it mirrors directory structure of `source` directory.
Pages are represented by their title and sorted alphabetically.

You can override the page title used in the navigation, pages order or hide page using the following AsciiDoc attributes.

page-nav-title::
  Title of the page used in the navigation.
  When not defined, the page title (i.e. top heading denoted by a single `=`) is used.

page-nav-weight::
  This attribute allows to alter position of the page in list of pages on the same level.
  The value must be an integer, default is 100.
  Lower number shifts page up, higher down.
  It may seem complicated, but it’s very simple – just a “multi-column sorting”.
  Pages are sorted by `(weight, title)`.

page-nav-hidden::
  If defined, the page (and all subpages) is not included in the navigation.

For example, if you want to use different title in navigation and push the page to the first place on its level:

[source, adoc]
----
= BigClown Alpha – Software Setup for macOS Host Platform
:page-nav-title: Software Setup for macOS
:page-nav-weight: 1
----

Only pages with a page title (i.e. top heading denoted by a single `=`) or attribute `page-nav-title` are included in navigation.
Each directory must contain file `index.adoc` that represents the page of the directory.
